### ISSUE TITLE
Hi，How long did it take you to train this model

### ISSUE THREAD

**Issue by haibin894609937** [lupantech/dual-mfa-vqa#2]
And GPU ？

**Comment by lupantech** [comment]
It mainly depends on GPU type, GPU number, RAM memory size and nccl optimization. If you use 4 Titan X GPUs, load all image features into memory and install nccl optimization, it will take 1-2 days to train the model. Training the model from a good checkpoint will accelarate the process and improve the final accuaracy in some degree.
